#!/usr/bin/env python3
"""
Countersign worksheet (ORDER-004 item 6) — the artifact the human session runs on.

One page per clean golden: the stem, the key figures, OUR derivation of them, and
where the full evidence lives. Chapter-stratified, so the session moves through
the corpus rather than through whatever sorted first — and so fatigue late in the
session does not land entirely on one chapter.

Design rules, each of which is a way the worksheet could quietly fail:

- **It must be auditable, not re-solvable.** The operator is checking worked
  evidence in ~2 minutes per item. Every figure therefore appears beside the key
  text it was matched against; an unpaired number is unreviewable.
- **Agreement is shown, not asserted.** "Matches key" is the claim under audit,
  so each figure carries the key value it corroborated against. If a figure
  cannot be paired to key text, it is listed under NOT PAIRED rather than
  silently dropped — the omission would be exactly the thing worth catching.
- **It is generated, never hand-edited.** It lands in deliverables/ and is
  rebuilt by deliver.sh, so a stale worksheet is visible in the stamp instead of
  arguable.

Written by deliver.sh; do not edit the output.
"""

import collections
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "out")
sys.path.insert(0, HERE)

import canon                      # noqa: E402
import compare_stage1_v3 as C     # noqa: E402
import countersign_packet as CP   # noqa: E402
import preflight as PF            # noqa: E402
import provenance as P            # noqa: E402

MAX_FIGS = 12          # per item: enough to audit, few enough to read


def key_context(value, key_text, width=64):
    """The key snippet a figure matched against, so agreement is visible."""
    kt = canon.delatex(key_text or "")
    v = canon.as_number(value)
    if v is None:
        return None
    for pat in (f"{v:,.0f}", f"{v:,.2f}", f"{abs(v):,.0f}"):
        i = kt.find(pat)
        if i != -1:
            s = re.sub(r"\s+", " ", kt[max(0, i - width // 2):i + width // 2])
            return s.strip()
    return None


def main():
    qs, known, amap = PF.load()
    gold_dir = os.path.join(HERE, "goldens")

    items = []
    for fn in sorted(os.listdir(gold_dir)):
        if not fn.endswith(".json") or fn == "INDEX.json":
            continue
        g = json.load(open(os.path.join(gold_dir, fn), encoding="utf-8"))
        if g.get("expected_verdict") != "PASS":
            continue
        q = qs.get(g["id"])
        if not q:
            continue
        src, why = P.evidence_dir(g["id"], q)
        if src is None:
            continue
        sol = json.load(open(os.path.join(src, "solver_output.json"), encoding="utf-8"))
        items.append({"g": g, "q": q, "sol": sol, "src": src,
                      "chapter": CP.chapter_of(q), "type": q.get("type")})

    # chapter-stratified: round-robin so no chapter clusters at the tired end
    buckets = collections.defaultdict(list)
    for it in items:
        buckets[it["chapter"]].append(it)
    for b in buckets.values():
        b.sort(key=lambda it: it["g"]["id"])
    order, keys, i = [], sorted(buckets, key=lambda k: (-len(buckets[k]), k)), 0
    while len(order) < len(items):
        k = keys[i % len(keys)]
        if buckets[k]:
            order.append(buckets[k].pop(0))
        i += 1

    L = []
    L.append("# Countersign worksheet\n")
    L.append("**Generated by `deliver.sh` — do not hand-edit.** "
             "Brief: `comms/operator/COUNTERSIGN-BRIEF.md`\n\n")
    L.append(f"**{len(order)} items**, chapter-stratified. Per item: agree → "
             "initial **PASS**. Any doubt → **QUERY** and move on.\n\n")
    by_ch = collections.Counter(it["chapter"] for it in order)
    by_ty = collections.Counter(it["type"] for it in order)
    L.append(f"Coverage — class: {dict(by_ty)} · chapters: "
             f"{dict(sorted(by_ch.items()))}\n\n")
    L.append("> **Scope.** Signing certifies floor #2 for the classes present "
             "here. MCQ items are outside the comparator's domain and are NOT "
             "covered by this session.\n\n---\n\n")

    for n, it in enumerate(order, 1):
        q, sol, g = it["q"], it["sol"], it["g"]
        kt = q.get("solution") or ""
        stem = re.sub(r"\s+", " ", canon.delatex(q.get("stem", ""))).strip()
        head = re.split(r"\*\*Required", canon.delatex(q.get("stem", "")))[0]
        head = re.sub(r"\s+", " ", head).strip()

        L.append(f"## {n}. `{g['id']}` — {it['chapter']} · {it['type']}\n\n")
        L.append(f"**Scenario.** {head[:600]}{'…' if len(head) > 600 else ''}\n\n")
        req = re.search(r"\*\*Required.*", canon.delatex(q.get("stem", "")), re.S)
        if req:
            L.append("**Required.** "
                     + re.sub(r"\s+", " ", req.group(0))[:420] + "\n\n")

        paired, unpaired = [], []
        for a in (sol.get("answers") or [])[:60]:
            v = canon.as_number(a.get("value"))
            if v is None:
                continue
            ctx = key_context(v, kt)
            (paired if ctx else unpaired).append((a.get("label"), v, ctx))

        L.append(f"**Our derivation vs the key** — {len(paired)} figure(s) "
                 f"paired to key text"
                 + (f", {len(unpaired)} not paired" if unpaired else "") + ":\n\n")
        L.append("| our figure | label | the key says |\n|---|---|---|\n")
        for lbl, v, ctx in paired[:MAX_FIGS]:
            L.append(f"| {v:,.2f} | {str(lbl)[:46]} | …{ctx[:70]}… |\n")
        if len(paired) > MAX_FIGS:
            L.append(f"| … | _{len(paired) - MAX_FIGS} more, all paired_ | |\n")
        L.append("\n")
        if unpaired:
            L.append(f"**NOT paired to key text ({len(unpaired)})** — these are "
                     "the ones worth your attention; the key may be silent on "
                     "them, or they may be ours alone:\n\n")
            for lbl, v, _ in unpaired[:6]:
                L.append(f"- {v:,.2f} — {str(lbl)[:70]}\n")
            if len(unpaired) > 6:
                L.append(f"- _…{len(unpaired) - 6} more_\n")
            L.append("\n")

        L.append(f"**Evidence.** `{os.path.relpath(it['src'], HERE)}` · "
                 f"tier `{g['provenance_tier']}` · guards "
                 f"`{g.get('guards_rule') or '—'}`\n\n")
        L.append("**Verdict:**  ☐ PASS   ☐ QUERY → _____________________\n\n---\n\n")

    L.append("## Sign-off\n\n")
    L.append(f"Items reviewed: ____ / {len(order)} · PASS: ____ · QUERY: ____\n\n")
    L.append("Then commit `comms/operator/DECISION-003-certified.md` with one "
             f"line: `CERTIFIED, n={len(order)}, <date>` plus any QUERY list.\n")

    dst = os.path.join(HERE, "deliverables", "countersign_worksheet.md")
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    open(dst, "w", encoding="utf-8").write("".join(L))
    print(f"  worksheet: {len(order)} items -> {os.path.relpath(dst, HERE)}")
    print(f"    class {dict(by_ty)} · chapters {len(by_ch)}")


if __name__ == "__main__":
    main()
